version: '2'

services:
  node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/node/app
    command: bash -c "npm install && npm start"
  
  # jatos:
  #   user: "root"
  #   image: jatos/jatos:latest
  #   expose:
  #     - "9000"
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - ./jatos_assets:/opt/docker/study_assets_root
  #   restart: always

  